version: "3"

services:
  update:
    # replace username/repo:tag with your name and image details
    image: tanzeemzillu/updateservicetest:updateservice-0.0.1
    deploy:
      mode: global
      update_config:
        delay: 20s
    ports:
      - 4000:8090

